### ISSUE TITLE
SCM command is not available. Please check settings on the administration panel.

### ISSUE THREAD

**Issue by hjpotter92** [jbox-web/redmine_git_hosting#691] opened 2017-08-24 15:11 UTC
I've gone through the closed #177 already. However, the log file states:

> 2017-08-24 20:34:17 +0530 [ERROR] Can't retrieve Git version: Non-zero exit code pid 31584 exit 129 for `sudo -n -u git -i /usr/bin/git --version --no-color`

when executing the same command (as `redmine` user), the output is:

```
redmine@redmine:~$ sudo -n -u git -i /usr/bin/git --version --no-color
error: unknown option `no-color'
usage: git version [<options>]

    --build-options       also print build options
```

**Comment by bs444** [comment] 2017-09-19 21:06
I just ran into this. It seems to:

**Be caused by:**
- The `git --version` command no longer accepting `--no-color`. (at least in Git 1.14.1)

**Causes:**
- The Redmine SCM system (Administration > Settings > Repositories) to register the Xitolite command as not available, and shows with a red exclamation (!).
- When creating a new repo, upon selecting "Gitolite" from the drop down, you get the message: `SCM command is not available. Please check settings on the administration panel.`

**Blocks:**
- The ability to create a new Gitolite repo.

**Possible workaround:**
- It doesn't seem to affect the ability to auto-create a repo on project-creation.

**Is fixed by:**
- I fixed it for my installation by editing [line 86 of /lib/redmine_git_hosting/commands/git.rb](https://github.com/jbox-web/redmine_git_hosting/blob/c1e0cc5476a711a18c294ad34f21e62348d5994e/lib/redmine_git_hosting/commands/git.rb#L86)
  to read:
`sudo_git('--version')` instead of `sudo_git('--version', '--no-color')`
and restarting apache.

**Closed** 2017-09-30 01:00 UTC

**Comment by rajadhava** [comment] 2019-09-02 09:59
Hi guys, I want to add something. I am using Redmine with below versions.

Redmine version 3.4.2.stable.16837
Ruby version   2.0.0-p648 (2015-12-16) [x86_64-linux]
Rails version  4.2.8
Git version 2.14

I got the same error when I tried to enable Git SCM command from the administration panel of the Redmine.
I fixed this issue. steps are given below:
1. _$ cd <Redmine Home>/lib/redmine/scm/adapters_
2. _$ vim git_adpater.rb_
3. at line no 57 you will see  **_shellout("#{sq_bin} --version --no-color") { |io| io.read }.to_s_**
4. change this line to **_shellout("#{sq_bin} --version") { |io| io.read }.to_s_**
5. Save the file
6. restart your Redmine service (Procedure depends on which web server you are using)

Hope this will work for you....
