### ISSUE TITLE
Cannot apply settings. Possibly related to #506.

### ISSUE THREAD

**Issue by HiTECNOLOGYs** [jbox-web/redmine_git_hosting#567] opened 2016-01-28 14:11 UTC
Same error here. I've got some extra plugins installed but I haven't had problem before recently. I tried downgrading to 3.1.3 (because 3.1.x is confirmed to work) but that didn't make the problem go away (probably due to database screwed up as well as files).

I'm kind of stuck here with working configuration that I would very much like to change but can't. It would be really great if there was a way I can adjust access configuration safely somehow as a temporary workaround.

I've been having this for probably quite a long time since I noticed it about a month ago but didn't have enough time to investigate back then.

The log says:

```
Completed 500 Internal Server Error in 3ms (ActiveRecord: 0.7ms)

ArgumentError (wrong number of arguments (1 for 0)):
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

And the versions are:

```
Environment:
  Redmine version                3.2.0.stable
  Ruby version                   2.1.7-p400 (2015-08-18) [x86_64-linux]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Git                            2.4.10
  Filesystem                     
  Xitolite                       2.4.10
Redmine plugins:
  redmine_bootstrap_kit          0.2.3
  redmine_checklists             3.1.3
  redmine_code_review            0.7.0
  redmine_dashboard              2.7.0
  redmine_git_hosting            1.2.0
  redmine_jenkins                1.0.1
```

Do ask any additional questions if you feel like I haven't provided enough information (because I feel I didn't).

Thanks!

**Comment by jblobb** [comment] 2016-02-05 02:26
Hi, I've just spent about a week pulling my hair out.

`Environment:
  Redmine version                3.1.3.stable.15144
  Ruby version                   1.9.3-p194 (2012-04-20) [x86_64-linux]
  Rails version                  4.2.5.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.17
  Git                            1.7.10.4
  Filesystem                     
  Xitolite                       1.7.10.4
Redmine plugins:
  redmine_bootstrap_kit          0.2.4
  redmine_git_hosting            1.2.0
  timelog_timer                  2.0.0`

So after using this install guide [http://redmine-git-hosting.io/get_started/](url), we noticed things missing. Eg, where does this go?

`repo    gitolite-admin
  RW+                            = redmine_gitolite_admin_id_rsa` 

This needs to be added into `conf/gitolite.conf`as per this guide [https://www.redmine.org/projects/redmine/wiki/HowTo_Install_Redmine_30x_on_Ubuntu_1404_with_Apache2_Phusion_Passenger_MySQL_Subversion_and_Git_(Gitolite)#MySQL](url)

Also we getting an "Internal error 500" when `tail -f -n 500 /redmine_install_dir/log/production.log`

We had to manually edit `/redmine_install_dir/plugins/redmine_git_hosting/lib/default_settings.yml` with our settings and run the following commands within the `/redmine/install/dir`:

`cd redmine
bundle install --without development test postgresql sqlite
RAILS_ENV=production rake redmine:plugins:migrate
RAILS_ENV=production rake redmine_git_hosting:update_repositories
RAILS_ENV=production rake redmine_git_hosting:fetch_changesets
RAILS_ENV=production rake redmine_git_hosting:restore_default_settings
RAILS_ENV=production rake redmine_git_hosting:install_hook_files
RAILS_ENV=production rake redmine_git_hosting:install_hook_parameters
RAILS_ENV=production rake redmine_git_hosting:install_gitolite_hooks`

Then for the safe side we restarted the server, and everything worked, when running "git commits" the comments would be there.

Don't hit "apply" or make changes for the "redmine_git_hosting" plugin via the gui it will break every time.

I hope this helps.

**Comment by HiTECNOLOGYs** [comment] 2016-02-08 08:28
@jblobb oh, thank you very much! That indeed did work and I managed to set settings to correct values.

I will leave the issue open for a time being since the GUI is still broken.

**Comment by n-rodriguez** [comment] 2016-12-29 00:14
Linked with https://github.com/jbox-web/redmine_git_hosting/issues/526

**Comment by n-rodriguez** [comment] 2016-12-30 01:05
I can't reproduce it with the next release (1.2.2) :

```
Environment:
  Redmine version                3.2.0.stable
  Ruby version                   2.1.7-p400 (2015-08-18) [x86_64-linux]
  Rails version                  4.2.5
  Environment                    development
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.10
  Mercurial                      3.1.2
  Git                            2.1.4
  Filesystem                     
  Xitolite                       2.1.4
Redmine plugins:
  redmine_bootstrap_kit          0.2.5
  redmine_git_hosting            1.2-devel
  redmine_sidekiq                2.1.0
```

Closing it.

**Closed by n-rodriguez** 2016-12-30 01:05 UTC
Labels: bug
