### ISSUE TITLE
Unable to init repository with README

### ISSUE THREAD

**Issue by hubiktomas** [jbox-web/redmine_git_hosting#574] opened 2016-02-25 10:38 UTC
Hello,

I am facing a following issue:

When I create a new gitolite repo and select to initialize it with README, the repo gets created, but not initialized.
```
2016-02-25 10:14:03 +0000 [INFO] User 'tomas.hubik' has created a new repository 'gfl/gfl-incubator/gfl_incubator'
2016-02-25 10:14:03 +0000 [WARN] add_repository : repository 'gfl/gfl-incubator/gfl_incubator' does not exist in Gitolite, create it ...
2016-02-25 10:14:03 +0000 [INFO] add_repository : commiting to Gitolite...
2016-02-25 10:14:03 +0000 [WARN] No matching item found for 'gfl/gfl-incubator/gfl_incubator' in Recycle Bin, exiting !
2016-02-25 10:14:03 +0000 [INFO] add_repository : let Gitolite create empty repository 'repositories/gfl/gfl-incubator/gfl_incubator.git'
2016-02-25 10:14:09 +0000 [INFO] Execute Gitolite Plugins
2016-02-25 10:14:09 +0000 [INFO] Creating README file for repository 'gfl/gfl-incubator/gfl_incubator'
2016-02-25 10:14:09 +0000 [ERROR] Error while creating README file for repository 'gfl/gfl-incubator/gfl_incubator'
2016-02-25 10:14:09 +0000 [ERROR] R access for gfl/gfl-incubator/gfl_incubator DENIED to admin
(Or there may be no repository at the given path. Did you spell it correctly?)
```
I think, that this issue is very similar to #475, but I am not using HTTPS.

In my gitolite.conf I have:
```
repo    @all
  RW+                            = redmine_gitolite_admin_id_rsa

repo    gfl/gfl-incubator/gfl_incubator
  RW+                            = redmine_tomas_hubik_1
  config redminegitolite.projectid = gfl-incubator
  config redminegitolite.repositoryid = gfl_incubator
  config redminegitolite.repositorykey = yHe0JRG4Pk9OakpCeS5HEAPdCMSuJfCc4wGxBqupKdPmQE2ntnGEB7PxgWpUXRje
  config http.uploadpack = false
  config http.receivepack = false
  config multimailhook.enabled = true
  config multimailhook.mailinglist = tomas.hubik@gfl.com
  config multimailhook.from = redmine@gfl.com
  config multimailhook.emailPrefix = [REDMINE]
```
When I check the repositories, I can see, that the repo is created, but not initialized.

When I initialize it manually and try to push to it, I get the following log output:
```
git.exe push --recurse-submodules=check --progress "origin" refs/heads/master:refs/heads/master
Counting objects: 42995   
Counting objects: 57867, done.
Delta compression using up to 8 threads.
Total 57866 (delta 23989), reused 0 (delta 0)
remote: [1G
remote: [1GNotifying Redmine about changes to this repository : 'gfl-incubator/gfl_incubator' ...
remote: [1GHTTP_ERROR : Net::ReadTimeout
remote: [1G
remote: [1GCalling additional post-receive hooks...
remote: [1G  - Executing extra hook 'hooks/post-receive.d/mail_notifications'
remote: Sending notification emails to: tomas.hubik@gfl.com
remote: [1G
remote: [1G
```
When I try to get changesets manually, I can see the repo in the redmine interface.

Can you, please, help?

Thank you very much in advance.

Best regards
Tomas

**Comment by hubiktomas** [comment] 2016-02-25 12:03
I forgot to add info about my system:

Environment:
  Redmine version                3.2.0.stable
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux-gnu]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               Mysql2
SCM:
  Mercurial                      3.1.2
  Git                            2.1.4
  Filesystem                     
  Xitolite                       2.1.4
Redmine plugins:
  redmine_bootstrap_kit          0.2.4
  redmine_git_hosting            1.2.0

Everything is green in the plugins config test.

Best regards
Tomas

**Comment by hubiktomas** [comment] 2016-03-08 16:56
Hello,

no ideas?

Thanks.

**Comment by hubiktomas** [comment] 2016-03-25 21:00
Hello,

any news there?

Tomas

**Comment by j0bb13** [comment] 2016-04-13 22:54
The problem is that "redmine_gitolite_admin_id_rsa" has RW+ access, but you're using access is DENIED to "admin". I suggest you add admin to the repo @all RW+ in the gitolite config ;)

(If you notice manual edits to the config file being removed from the file (which happened with me), stop Redmine and clear the cache, then edit the Gitlite config and then start Redmine again)

Good luck!

**Comment by n-rodriguez** [comment] 2016-10-13 20:14
@jobhh Good point! Thank you :)

```2016-02-25 10:14:09 +0000 [ERROR] R access for gfl/gfl-incubator/gfl_incubator DENIED to admin```

@hubiktomas you **must not** reuse the Redmine SSH key and assign it to a user.

**Closed by n-rodriguez** 2016-10-13 20:14 UTC
