### ISSUE TITLE
Redmine overwrites my gitolite configuration

### ISSUE THREAD

**Issue by hjpotter92** [jbox-web/redmine_git_hosting#552] opened 2015-12-11 14:48 UTC
> Also posted on [gitolite Google group](https://groups.google.com/d/msg/gitolite/xcDVcepF4Kw/lziKjgVhCQAJ)

A few weeks ago, right after installing gitolite and setting up redmine, I edited `gitolite.conf` file to put the following in it:

```
repo @all
    RW+          = admin @all
```

Later on, I created a repository using gitolite commands (without relying on redmine). Let's call this `some-repo`. So, when I do the following:

```
ssh git@myserver info
```

I (and everyone else) am shown `R W` access on all repositories. So far, so fine. On the git/redmine server, I login as `git` user and do the following:
1. Edit `projects.list` to remove `some-repo` from it
2. `rm -rf repositories/some-repo.git`

Now, I switch to `redmine` user to edit the `gitolite.conf` file and remove the previous inclusion I had done. I commit and push the changes. Doing the following now shows me correct permissions:

```
ssh git@myuser info
```

The output shows no project named `some-repo`, and proper permissions for the several other projects created via redmine. Now, I login to redmine and visit settings for any of my project, tweak anything and as soon as I save it; I get the following commit in `gitolite-admin` repository:

> [gitolite-rugged] Merged `origin/master` into `master`

So, the repo's log is like:

```
$ git log --graph --oneline 
    * 0c73c10 update_repository : my/project/repo 
    *   9d789f9 [gitolite-rugged] Merged `origin/master` into `master` 
    |\ 
    | * 2d203fc Deny RW+ acess to @all 
    |/ 
    * e1a3e60 disable_readme_creation : Disable README file creation for repositories 
```

I understand that `gitolite-rugged` here is somehow caching my conf file from before and overwriting the changes I make on `gitolite-admin` repository. Is there anyway to resolve the issue?

**Comment by SomeBdyElse** [comment] 2015-12-17 09:02
Hey @hjpotter92 . This sounds familiar. Please check, whether this could be a duplicate of #546

**Comment by hjpotter92** [comment] 2015-12-17 11:40
@SomeBdyElse Yes. I have also tried to:

1. Stop redmine server
1. Clear all caches with `rake`
1. Committing to `gitolite-admin` with the redmine server still stopped.
1. Starting the server.

gitolite-rugged still overwrites the changes.

**Comment by gcolpart** [comment] 2016-09-20 10:58
Hello,

Firstly: thanks @n-rodriguez for your awesome Redmine plugin, many kudos to you!

I have exactly the same bug. If you modify Gitolite configuration manually (with gitolite-admin repository), it's overwritten by "gitolite-rugged" merge commit. With this bug, part of documentation http://redmine-git-hosting.io/configuration/notes/#interaction-with-non-redmine-gitolite-users is wrong.

**Comment by hjpotter92** [comment] 2016-10-11 12:26
@n-rodriguez Any quickfix to reset the global `@all` access?

**Comment by PowerKiKi** [comment] 2019-12-02 09:12
As discussed in https://github.com/jbox-web/redmine_git_hosting/issues/732#issuecomment-532362560, issues related to Redmine < 4.0 or severely outdated issues are being closed to help clean up the issue tracker.

If this issue is still relevant to you and you are running Redmine >= 4.0, please open a new issue including all new relevant information.

**Closed by PowerKiKi** 2019-12-02 09:12 UTC
Labels: bug
