### ISSUE TITLE
After upgrade to 1.0, Redmine won't show changesets

### ISSUE THREAD

**Issue by saz** [jbox-web/redmine_git_hosting#364] opened 2015-02-23 15:55 UTC
I've upgraded to the new stable version 1.0, but after the upgrade, Redmine no longer shows any changesets. All commits have a ```refs #1234``` or ```fixes #1234``` are not shown at the issue detail view.

Hooks seem to be working, as the following is shown, if I'm running the hooks in non-async mode with debugging enabled:

```
remote:
remote: Notifying Redmine about changes to this repository : 'herocentral/' ...
remote: Looking for additional global post-receive hooks...
remote:
remote: Looking for additional local post-receive hooks...
remote:   - No local hooks found
remote:
remote: Calling additional post-receive hooks...
remote:   - Executing extra hook 'hooks/post-receive.d/mail_notifications'
remote:     multimailhook is disabled
remote:
```

**Comment by saz** [comment] 2015-02-23 15:56
The only strange thing I can see, is the repository name, as the repository URL for cloning is
```ssh://gitolite@redmine.example.com/entwicklung-allgemein/herocentral.git```

**Comment by saz** [comment] 2015-02-23 16:09
.gitconfig content:

```
[hooks "redmine_gitolite"]
        url = http://tracker.example.com/githooks/post-receive
        debug = true
        asynch = true
[redminegitolite]
        redmineurl = http://tracker.example.com/githooks/post-receive/redmine
        debugmode = true
        asyncmode = false
[multimailhook]
        mailer = sendmail
        environment = gitolite
        smtpauth = false
        smtpserver = localhost
        smtpport = 25
```

My Redmine installation is using ```https://```, this is the only obvious error I'm seeing in this URL (but it gets redirected, at least in the browser).

Trying to open redmineurl, will result in a 404 Page not found error message, but I don't know, if there is a part of the URL missing.

**Comment by saz** [comment] 2015-02-23 16:11
I've fixed the hooks URL in the settings.

**Comment by saz** [comment] 2015-02-23 16:15
It's working now. Maybe there should be an error message, if the hooks URL isn't working. Now it's showing the following during a push:

```
remote:
remote: Notifying Redmine about changes to this repository : 'herocentral/' ...
remote:
remote:   - Fetching changesets for 'herocentral' repository ...  [success]
remote:
remote: Looking for additional global post-receive hooks...
remote:
remote: Looking for additional local post-receive hooks...
remote:   - No local hooks found
remote:
remote: Calling additional post-receive hooks...
remote:   - Executing extra hook 'hooks/post-receive.d/mail_notifications'
remote:     multimailhook is disabled
remote:
```

**Comment by n-rodriguez** [comment] 2015-02-24 19:35
> My Redmine installation is using https://, this is the only obvious error I'm seeing in this URL (but it gets redirected, at least in the browser).

This is the cause of the 'bug'. The hook expect a 200 status code and not a 301.

**Comment by n-rodriguez** [comment] 2015-02-24 20:46
Fixed in commit https://github.com/jbox-web/redmine_git_hosting/commit/cbb6f0028afba0d611bbbc13ed9e2b62595177e1

Hook will throw an error if the status code is not a 200.

**Closed** 2015-02-24 20:47 UTC
Labels: enhancement
