### ISSUE TITLE
HTTPS Push (Popen : wrong number of arguments)

### ISSUE THREAD

**Issue by BAndonovski** [jbox-web/redmine_git_hosting#345] opened 2015-02-03 16:10 UTC
This is the set up:
```
Ruby 1.9
Rails 3.2
Redmine 2.6.1
jbox's redmine_git_hosting plugin
```

Trying to use git repo through HTTPS. Clone works fine. Push starts and hangs at
```
Counting objects: 3, done.
Writing objects: 100% (3/3), 206 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
```

Apache says the issue is:
```
App 1013 stderr: [ 2015-02-03 16:33:59.3105 1036/0x0000000782d9b0(Worker 1) utils.rb:68 ]: *** Exception ArgumentError in Rack body object #each method (wrong number of arguments (3 for 1..2)) (process 1036, thread 0x0000000782d9b0(Worker 1)):
App 1013 stderr: from /home/r2d2/.bundler/ruby/1.9.1/grack-971b468103ac/lib/grack/server.rb:78:in popen' App 1013 stderr: from /home/r2d2/.bundler/ruby/1.9.1/grack-971b468103ac/lib/grack/server.rb:78:inblock in service_rpc'
App 1013 stderr: from /usr/lib/ruby/vendor_ruby/rack/response.rb:89:in call' App 1013 stderr: from /usr/lib/ruby/vendor_ruby/rack/response.rb:89:ineach'
App 1013 stderr: from /usr/lib/ruby/vendor_ruby/rack/body_proxy.rb:31:in each' App 1013 stderr: from /var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/query_cache.rb:46:ineach'
App 1013 stderr: from /var/lib/gems/1.9.1/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:460:in each' App 1013 stderr: from /usr/lib/ruby/vendor_ruby/rack/body_proxy.rb:31:ineach'
App 1013 stderr: from /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:140:in process_request' App 1013 stderr: from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:142:inaccept_and_process_next_request'
App 1013 stderr: from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in main_loop' App 1013 stderr: from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:448:inblock (3 levels) in start_threads'
```

**Comment by dgeo** [comment] 2015-02-03 18:15
can it be related with https://jbox-web.github.io/redmine_git_hosting/configuration/troubleshooting/#hook-errors-while-pushing-over-https ?

**Comment by BAndonovski** [comment] 2015-02-03 18:52
Unfortunately, no. Those are already set as described there.
Besides, I don't think the request even gets that far because of the
exception.

**Comment by BAndonovski** [comment] 2015-02-04 14:29
Any ideas / suggestions / fix-es would be appreciated. 

@n-rodriguez This is a great plug in and is really mission critical for me at the moment. A big set up is depending (and currently not working) because of this issue. I'd really appreciate your help on this. 
Let's solve the issue and test that donation button if it's working :)

**Comment by n-rodriguez** [comment] 2015-02-04 23:44
> @n-rodriguez This is a great plug in and is really mission critical for me at the moment. A big set up is depending (and currently not working) because of this issue.

I understand your stress and the emergency of your case but I'm very busy this time :
I've also a [business to run](http://www.jbox-web.com) and these days it's the first priority.

**Comment by BAndonovski** [comment] 2015-02-05 11:07
@n-rodriguez I fully understand and appreciate that. Hence my offer of making fixing the bug be worth your while. 
Based on the call stack, I expect it to be a pretty quick fix for anyone familiar with the code and really hope you'd find the time to help me out.

**Comment by BAndonovski** [comment] 2015-02-05 13:00
I believe I have solved it. It seems to be working now. 
Maybe you can just confirm the ramifications of my fix, am I braking something else, since this has been my first intervention in a ruby code :) 


There are a couple of popen calls in the file mentioned in the stack. 
Based on the documentation on different ruby versions and expected parameters, I removed the popen_env parameter.

Did a couple of tests now, seems to be working.

**Comment by n-rodriguez** [comment] 2015-02-25 05:13
@BAndonovski : actually the issue is your Ruby version : 

http://ruby-doc.org//core-1.9.3/IO.html#method-c-popen
http://ruby-doc.org//core-2.1.0/IO.html#method-c-popen

[Support of Ruby 1.9.x has ended](https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/) so I highly recommend you to upgrade to Ruby 2.1 or 2.0.0.

**Comment by n-rodriguez** [comment] 2015-02-25 23:26
No more need to edit files. Fixed in commit https://github.com/jbox-web/redmine_git_hosting/commit/73c4d150572b6b29182043b88814d847f930da30 (the compatibility patch will be removed with Debian Jessie release)

**Closed by n-rodriguez** 2015-02-25 23:26 UTC
Labels: bug
